defstudio/telegraph

docs/content/en/features/telegraph-response.md, src/Client/TelegraphResponse.php, src/Support/Testing/Fakes/TelegraphFake.php, src/Telegraph.php, tests/Pest.php, tests/Unit/Client/TelegraphResponseTest.php, tests/Unit/TelegraphTest.php, tests/__snapshots__/TelegraphResponseTest__it_wraps_original_response__1.json
=> wraps response to TelegraphResponse to return status and messageId

src/Keyboard/Keyboard.php
=> removed mistyped semicolon

src/Handlers/WebhookHandler.php, src/Keyboard/Button.php, src/Keyboard/Keyboard.php
This PR will refactor the Keyboard code to get it ready for some improvements
=> chore: keyboard refactor

docs/content/en/features/messages.md, src/Concerns/ComposesMessages.php, src/Concerns/InteractsWithTelegram.php, src/Concerns/ManagesKeyboards.php, src/Facades/Telegraph.php, src/Support/Testing/Fakes/TelegraphFake.php, src/Telegraph.php, tests/Pest.php, tests/Unit/Concerns/ComposesMessagesTest.php, tests/Unit/Facades/TelegraphTest.php, tests/__snapshots__/ComposesMessagesTest__it_can_send_protected_content__1.txt
```php
$chat->message("please don't share this")->protectContent()->send();
```
close #26
=> add protect content message option

docs/content/en/features/messages.md, src/Concerns/ComposesMessages.php, tests/Unit/Concerns/ComposesMessagesTest.php, tests/__snapshots__/ComposesMessagesTest__it_can_send_silent_messages__1.txt
```php
$chat->message("late night message")->silent()->send();
```
close #25
=> add silent message option

docs/content/en/features/messages.md, src/Concerns/ComposesMessages.php, tests/Unit/Concerns/ComposesMessagesTest.php, tests/__snapshots__/ComposesMessagesTest__it_can_disable_url_preview__1.txt
```php
$chat->message("http://my-blog.dev")->withoutPreview()->send();
```
close #24
=> add withoutPreview message option

docs/content/en/models/telegraph-bot.md, docs/content/en/models/telegraph-chat.md, docs/content/en/testing/assertions.md, docs/content/en/testing/fake.md, docs/content/en/webhooks/callback-data.md, docs/content/en/webhooks/callback-reply.md, docs/content/en/webhooks/keyboard-interaction.md, docs/content/en/webhooks/overview.md, docs/content/en/webhooks/webook-request-types.md, src/Models/TelegraphBot.php, tests/Unit/Models/TelegraphBotTest.php, tests/__snapshots__/TelegraphBotTest__it_can_retrieve_its_url__1.txt
```php
$telegraphBot->url();
// https://t.me/my-bot-name
```
close #23
=> add url method to TelegraphBot

docs/content/en/features/messages.md, src/Concerns/ComposesMessages.php, tests/Unit/Concerns/ComposesMessagesTest.php, tests/__snapshots__/ComposesMessagesTest__it_can_reply_to_a_message__1.txt
```php
$chat->message("ok!")->reply(123456)->send();
```
close #27
=> add reply message option

docs/content/en/features/messages.md, docs/content/en/features/telegram-api-calls.md, docs/content/en/features/telegraph-facade.md, docs/content/en/models/telegraph-bot.md, docs/content/en/models/telegraph-chat.md, docs/content/en/quickstart/register-new-chat.md, docs/content/en/webhooks/deleting-webhooks.md, docs/content/en/webhooks/manual-polling.md, docs/content/en/webhooks/overview.md, src/Concerns/ComposesMessages.php, src/Facades/Telegraph.php, src/Models/TelegraphChat.php, src/Telegraph.php, tests/Pest.php, tests/Unit/Concerns/ComposesMessagesTest.php, tests/__snapshots__/ComposesMessagesTest__it_can_delete_a_message__1.txt
=> feat: delete message

docs/content/en/features/messages.md, src/Concerns/ComposesMessages.php, src/Telegraph.php, tests/Unit/Concerns/ComposesMessagesTest.php, tests/__snapshots__/ComposesMessagesTest__it_can_edit_a_message_with_data_set_edit_after_text__1.txt, tests/__snapshots__/ComposesMessagesTest__it_can_edit_a_message_with_data_set_edit_before_text__1.txt
=> feat: edit message

src/DTO/CallbackQuery.php, src/DTO/ChatMember.php, src/DTO/ChatMemberUpdate.php, src/DTO/TelegramUpdate.php, src/Facades/Telegraph.php, src/Handlers/WebhookHandler.php, tests/Unit/DTO/TelegramUpdateTest.php, tests/Unit/Handlers/WebhookHandlerTest.php
=> fix: allows parameters and @bot reference after command

src/Concerns/ManagesKeyboards.php
Fixes the issue https://github.com/def-studio/telegraph/issues/58
=> Fix keyboard not being removed

src/Concerns/ComposesMessages.php, src/Concerns/HasBotsAndChats.php, src/Concerns/InteractsWithWebhooks.php, src/Concerns/ManagesKeyboards.php, src/Concerns/SendsFiles.php, src/Facades/Telegraph.php, src/Support/Testing/Fakes/TelegraphFake.php, tests/Pest.php, tests/Regression/Issue64LeakingState.php, tests/Unit/Concerns/ComposesMessagesTest.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/Unit/Concerns/InteractsWithWebhooksTest.php, tests/Unit/Concerns/ManagesKeyboardsTest.php, tests/Unit/Concerns/SendsFilesTest.php
=> fix leaking state

config/telegraph.php, docs/content/en/models/telegraph-bot.md, docs/content/en/models/telegraph-chat.md, src/Models/TelegraphBot.php, src/Models/TelegraphChat.php
This PR will allow customization on models.
=> feat: bot and chat models customization

docs/content/en/features/keyboards.md, src/Keyboard/Button.php, src/Keyboard/Keyboard.php, tests/Sandbox/TelegraphTest.php, tests/Unit/Keyboard/KeyboardTest.php
This PR will add a new keyboard button type: Web App url
=> Web app inline keyboard

docs/content/en/webhooks/webhook-request-types.md, src/Handlers/WebhookHandler.php
prevent /handle commands to be used in webhooks
fix #86
=> fix forbidden /handle command

docs/content/en/webhooks/dto.md, src/DTO/Message.php, src/Support/Testing/Fakes/TelegraphFake.php, tests/Feature/Commands/CreateNewBotCommandTest.php, tests/Feature/Commands/CreateNewChatCommandTest.php, tests/Feature/Commands/GetTelegramWebhookDebugInfoCommandTest.php, tests/Feature/Commands/SetTelegramWebhookCommandTest.php, tests/Feature/Commands/UnsetTelegramWebhookCommandTest.php, tests/Sandbox/TelegraphTest.php, tests/Unit/Client/TelegraphResponseTest.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/Unit/DTO/MessageTest.php, tests/Unit/Models/TelegraphBotTest.php, tests/Unit/Models/TelegraphChatTest.php, tests/Unit/Support/Testing/TelegraphFakeTest.php
=> [Feat] Reply to support

src/Handlers/WebhookHandler.php
=> [Fix] chat id retrieval for messages incoming from channels

docs/content/en/features/keyboards.md, docs/content/en/features/telegram-api-calls.md, src/Keyboard/Keyboard.php, src/Keyboard/ReplyKeyboard.php, src/Telegraph.php, tests/Unit/Keyboard/KeyboardTest.php, tests/Unit/Keyboard/ReplyKeyboardTest.php, tests/Unit/TelegraphTest.php
add a method in Telegraph for if true run & if false don't run
like when function in Elquent Laravel
=> [feat] conditional methods

src/Handlers/WebhookHandler.php
=> [fix] new webhook chats not being created

docs/content/en/webhooks/webhook-request-types.md, src/Handlers/WebhookHandler.php, tests/Support/TestWebhookHandler.php, tests/Unit/Handlers/WebhookHandlerTest.php
=> [feat] command parameters

config/telegraph.php, docs/content/en/installation.md, docs/content/en/webhooks/webhook-request-types.md, src/Handlers/WebhookHandler.php, tests/Support/TestWebhookHandler.php, tests/Unit/Handlers/WebhookHandlerTest.php
=> [feat] unknown commands handling

docs/content/en/features/attachments.md, src/Concerns/SendsAttachments.php, src/DTO/Attachment.php, tests/Unit/Concerns/SendsAttachmentsTest.php, tests/Unit/Models/TelegraphChatTest.php
=> [feat] attachments remote url and file_id

config/telegraph.php, docs/content/en/installation.md, docs/content/en/webhooks/overview.md, src/DTO/Chat.php, src/Handlers/WebhookHandler.php, tests/Pest.php, tests/Unit/Handlers/WebhookHandlerTest.php, tests/__snapshots__/TelegraphBotTest__it_can_poll_for_updates__1.yml
=> [feat] unknown chats webhook handling

docs/content/en/features/telegram-api-calls.md, docs/content/en/models/telegraph-chat.md, src/Concerns/HasBotsAndChats.php, src/Facades/Telegraph.php, src/Models/TelegraphChat.php, src/Support/Testing/Fakes/TelegraphFake.php, src/Telegraph.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/Unit/Models/TelegraphChatTest.php, tests/__snapshots__/HasBotsAndChatsTest__it_can_retrieve_chat_member_count__1.yml
=> [feat] chat member count

docs/content/en/features/telegram-api-calls.md, docs/content/en/models/telegraph-chat.md, src/Concerns/HasBotsAndChats.php, src/Enums/ChatPermissions.php, src/Facades/Telegraph.php, src/Models/TelegraphChat.php, src/Telegraph.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/Unit/Models/TelegraphChatTest.php, tests/__snapshots__/HasBotsAndChatsTest__it_can_set_chat_permissions__1.yml
=> [feat] chat permissions

src/Concerns/HasBotsAndChats.php, src/Models/TelegraphChat.php, src/Telegraph.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/Unit/Models/TelegraphChatTest.php, tests/__snapshots__/HasBotsAndChatsTest__it_can_delete_chat_photo__1.yml
Implements method for deleting chat photo.
Closes #191
=> Implement `deleteChatPhoto` method

composer.json, docs/content/en/features/messages.md, src/Concerns/ManagesKeyboards.php, src/Exceptions/KeyboardException.php, tests/Unit/Concerns/ManagesKeyboardsTest.php, tests/__snapshots__/ManagesKeyboardsTest__it_can_force_a_reply__1.yml, tests/__snapshots__/ManagesKeyboardsTest__it_can_force_a_reply_selectively__1.yml, tests/__snapshots__/ManagesKeyboardsTest__it_can_force_a_reply_with_placeholder__1.yml
implements forced replies
ref: https://core.telegram.org/bots/api#forcereply
#210
=> [feat] forced replies

docs/content/en/webhooks/dto.md, docs/content/en/webhooks/webhook-request-types.md, src/DTO/InlineQueryResultArticle.php, tests/Unit/Concerns/AnswersInlineQueriesTest.php, tests/Unit/DTO/InlineQueryResultArticleTest.php, tests/__snapshots__/AnswersInlineQueriesTest__it_can_answer_an_inline_query__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_offer_to_switch_to_private_message__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_set_cache_duration__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_set_next_offset__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_set_results_as_personal__1.yml
=> Fix issue #196

docs/content/en/webhooks/dto.md, docs/content/en/webhooks/webhook-request-types.md, src/DTO/InlineQueryResultMpeg4Gif.php, tests/Unit/Concerns/AnswersInlineQueriesTest.php, tests/Unit/DTO/InlineQueryResultMpeg4GifTest.php, tests/__snapshots__/AnswersInlineQueriesTest__it_can_answer_an_inline_query__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_offer_to_switch_to_private_message__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_set_cache_duration__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_set_next_offset__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_set_results_as_personal__1.yml
=> Fix issue #197

docs/content/en/webhooks/dto.md, docs/content/en/webhooks/webhook-request-types.md, src/DTO/InlineQueryResultVideo.php, tests/Unit/Concerns/AnswersInlineQueriesTest.php, tests/Unit/DTO/InlineQueryResultVideoTest.php, tests/__snapshots__/AnswersInlineQueriesTest__it_can_answer_an_inline_query__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_offer_to_switch_to_private_message__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_set_cache_duration__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_set_next_offset__1.yml, tests/__snapshots__/AnswersInlineQueriesTest__it_can_set_results_as_personal__1.yml
=> Fix issue #198

README.md, config/telegraph.php, resources/lang/en/validation.php, src/Handlers/EmptyWebhookHandler.php, src/Handlers/WebhookHandler.php, src/TelegraphServiceProvider.php
So that a person can change the message without getting into the internal code
=> Add validate error to config

src/Handlers/WebhookHandler.php
added the protected setupChat method to override the chat entity
=> Setup chat

src/Facades/Telegraph.php
=> fix chatInfo error

docs/content/en/features/keyboards.md, src/Keyboard/Button.php, tests/Unit/Keyboards/KeyboardTest.php
added switch_inline_query button . The value can be empty and return only the bot's username . I set it like an empty string and not like a null/string value . If i'm wrong, i will fix it.
=> implement switch inline query type in button with relative test and doc

docs/content/en/features/telegram-api-calls.md, src/Concerns/InteractWithUsers.php, src/Facades/Telegraph.php, src/Telegraph.php, tests/Unit/Concerns/InteractsWithUsersTest.php, tests/__snapshots__/InteractsWithUsersTest__it_can_retrieve_user_profile_photos__1.yml
implemented the getUserProfilePhotos with new Concern "InteractWithUsers", doc and test(with relative snapshot)
=> Implement get user profile photos

docs/content/en/features/telegram-api-calls.md, src/Concerns/HasBotsAndChats.php, src/Facades/Telegraph.php, src/Telegraph.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/__snapshots__/HasBotsAndChatsTest__it_can_retrieve_a_chat_member__1.yml
closes #259 
Telegram API getChatMember method is implemented as chatMember.
=> chatMember method implemented

docs/content/en/features/telegram-api-calls.md
Hello, in this changes I set caption of button
=> Change caption of button

docs/content/en/webhooks/webhook-request-types.md
Hello, in this change i edit info about gettng any content from message
=> [docs] added suggestion on contact verification

docs/content/en/webhooks/dto.md
close #307 implemented animation  in "dto doc"
=> [docs] add Animation DTO in documentation

docs/content/en/features/attachments.md, docs/content/en/features/telegram-api-calls.md, src/Concerns/SendsAttachments.php, src/Facades/Telegraph.php, src/Models/TelegraphChat.php, src/Telegraph.php, tests/Unit/Concerns/SendsAttachmentsTest.php, tests/Unit/Models/TelegraphChatTest.php, tests/__snapshots__/SendsAttachmentsTest__it_can_send_a_contact__1.yml
close #187 implemented sendContact method with relative test, doc and snapshot
=> [feat] SendContact Method

docs/content/en/webhooks/dto.md
fix #316 fixed doc "dto" reference
=> #316 docs reference error

src/Concerns/ManagesKeyboards.php
=> fix keyboards

src/DTO/TelegramUpdate.php, src/Handlers/WebhookHandler.php, tests/Unit/DTO/TelegramUpdateTest.php
close #374 implement edited_message optional parameter in TelegramUpdate.php
=> TelegramUpdate new optional parameter (edited_message)

src/Models/TelegraphBot.php, src/Models/TelegraphChat.php
now we can write custom Factory for models
=> write custom Factory

docs.bak/content/en/webhooks/callback-data.md, src/Handlers/WebhookHandler.php, tests/Support/TestWebhookHandler.php, tests/Unit/Handlers/WebhookHandlerTest.php
implements #423 removing some conflicts
Co-authored-by: @armvit
=> Automatic dependencies resolution for callback action method

docs/content/13.models/2.telegraph-chat.md, src/DTO/ChatMember.php, src/DTO/Message.php, src/Models/TelegraphChat.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/Unit/Models/TelegraphChatTest.php
#421 implement memberInfo() method + docs
=> #421 implement memberInfo() method + docs

src/DTO/Animation.php, src/DTO/Audio.php, src/DTO/CallbackQuery.php, src/DTO/Chat.php, src/DTO/ChatMember.php, src/DTO/ChatMemberUpdate.php, src/DTO/Contact.php, src/DTO/Document.php, src/DTO/InlineQuery.php, src/DTO/InlineQueryResult.php, src/DTO/InlineQueryResultArticle.php, src/DTO/InlineQueryResultAudio.php, src/DTO/InlineQueryResultContact.php, src/DTO/InlineQueryResultDocument.php, src/DTO/InlineQueryResultGif.php, src/DTO/InlineQueryResultLocation.php, src/DTO/InlineQueryResultMpeg4Gif.php, src/DTO/InlineQueryResultPhoto.php, src/DTO/InlineQueryResultVideo.php, src/DTO/InlineQueryResultVoice.php, src/DTO/Location.php, src/DTO/Message.php, src/DTO/Photo.php, src/DTO/TelegramUpdate.php, src/DTO/User.php, src/DTO/Video.php, src/DTO/Voice.php, tests/__snapshots__/TelegraphBotTest__it_can_poll_for_updates__1.yml
=> [fix] DTO lose false values

docs/content/12.features/8.telegram-api-calls.md, docs/content/13.models/1.telegraph-bot.md, src/Concerns/HasBotsAndChats.php, src/Models/TelegraphBot.php
=> [feat] botUpdates timeout, offset and limit

src/Concerns/SendsAttachments.php
=> [Fix] breaking change on minor version

config/telegraph.php, docs/content/14.webhooks/1.overview.md, docs/content/14.webhooks/2.registering-webhooks.md, docs/content/2.installation.md, routes/api.php, src/Concerns/InteractsWithWebhooks.php, src/Controllers/WebhookController.php, src/Handlers/WebhookHandler.php, src/Keyboard/Keyboard.php, tests/Feature/Webhooks/WebhookTest.php, tests/Pest.php, tests/Unit/Concerns/InteractsWithWebhooksTest.php
This PR will all middleware support for webhook route
closes #536 
closes #515
=> Wehbook middleware

routes/api.php, src/Concerns/InteractsWithWebhooks.php, src/Controllers/WebhookController.php, src/Handlers/WebhookHandler.php
This PR will fix the issue pointed out in #566  and extends the fix to other parts involved
=> Fix breaking change in minor release

docs/12.features/4.reply-keyboards.md
close #586 fix documentation error
=> #586 fix documentation error

.gitignore, config/telegraph.php, docs/14.webhooks/1.overview.md, phpunit.xml.dist, src/Concerns/InteractsWithTelegram.php, src/Concerns/SendsAttachments.php, src/DTO/InlineQueryResultArticle.php, src/DTO/InlineQueryResultContact.php, src/DTO/InlineQueryResultLocation.php, src/Jobs/SendRequestToTelegramJob.php, tests/TestCase.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/Unit/Concerns/SendsAttachmentsTest.php, tests/Unit/Handlers/WebhookHandlerTest.php
close #591 implemented HTTP request timeout config value + lint
=> #591 implemented HTTP request timeout config value

src/Keyboard/Keyboard.php, src/Keyboard/ReplyKeyboard.php, src/Telegraph.php
Laravel has a Conditionable trait for when() and unless() logic. I replaced this function with that.
=> feat: replace when functions with Laravel Conditionable

docs/12.features/9.dto.md, src/Concerns/FakesRequests.php, src/DTO/User.php, tests/.pest/snapshots/Unit/Models/TelegraphBotTest/it_can_poll_for_updates.snap, tests/Unit/DTO/MessageTest.php, tests/Unit/DTO/UserTest.php
Hi @fabio-ivona 
Thanks for your package.
I added the isPremium() function to DTO User and also added to the documentation.
Please merge it and release a new version so I can use it in my application.
[Tg Api Documentation](https://core.telegram.org/bots/api#user)
=> feat: add isPremium to DTO User

docs/12.features/7.attachments.md, docs/12.features/8.telegram-api-calls.md, docs/13.models/2.telegraph-chat.md, src/Facades/Telegraph.php, src/Handlers/WebhookHandler.php, src/Models/TelegraphChat.php, src/Telegraph.php, tests/Unit/Models/TelegraphChatTest.php
#386-implemented-thread-method
=> #386-implemented-thread-method

docs/12.features/9.dto.md, src/DTO/Message.php, src/DTO/WriteAccessAllowed.php, tests/Unit/DTO/MessageTest.php, tests/Unit/DTO/WriteAccessAllowedTest.php
implemented WriteAccessAllowed
link to Core Docs: https://core.telegram.org/bots/api#writeaccessallowed
=> [feat] write access allowed field

src/DTO/User.php
Hi,
I want to use this DTO for [webapp user](https://core.telegram.org/bots/webapps#webappuser). 
just Is_bot is Optional in the web app.
=> Fix UserDTO

src/Handlers/WebhookHandler.php
=> [fix] exceptions in onFailure method

docs/13.api/2.chats.md, src/Concerns/HasBotsAndChats.php, src/Telegraph.php, tests/Unit/Concerns/HasBotsAndChatsTest.php
https://core.telegram.org/bots/api#getchatadministrators
=> [feat] chatAdministrators call

src/Concerns/HasBotsAndChats.php, src/Models/TelegraphChat.php, src/Telegraph.php, tests/Unit/Models/TelegraphChatTest.php
Hi, added some methods for closed chats
=> [feat] chat join request management

config/telegraph.php, docs/2.installation.md, src/Concerns/InteractsWithTelegram.php, src/DTO/Message.php, src/Jobs/SendRequestToTelegramJob.php
close #635 implement config for connection request timeout
=> #635 implement config for connection request timeout

docs/12.features/9.dto.md, docs/15.webhooks/4.webhook-request-types.md, src/DTO/ChatInviteLink.php, src/DTO/ChatJoinRequest.php, src/Facades/Telegraph.php, src/Handlers/WebhookHandler.php, src/Support/Testing/Fakes/TelegraphFake.php, tests/Pest.php, tests/Support/TestWebhookHandler.php, tests/Unit/DTO/ChatInviteLinkTest.php, tests/Unit/DTO/ChatJoinRequestTest.php, tests/Unit/Handlers/WebhookHandlerTest.php
Telegram doc: https://core.telegram.org/bots/api#chatjoinrequest
=> Support for handling webhook requests to join chats/channels

src/DTO/InlineQueryResultArticle.php, src/Handlers/WebhookHandler.php, src/Keyboard/Keyboard.php, src/Telegraph.php
support for php 8.4.
Deprecated
=> support for php 8.4

docs/14.models/2.telegraph-chat.md, src/Concerns/HasBotsAndChats.php, src/Models/TelegraphChat.php
https://core.telegram.org/bots/api#unbanchatmember
=> add only_if_banned flag to banMemer

docs/12.features/7.attachments.md, docs/12.features/9.dto.md, docs/14.models/2.telegraph-chat.md, src/Concerns/SendsAttachments.php, src/DTO/Location.php, src/DTO/Message.php, src/DTO/Venue.php, src/Models/TelegraphChat.php, src/Telegraph.php, tests/.pest/snapshots/Unit/Concerns/SendsAttachmentsTest/it_can_send_a_venue_message.snap, tests/Unit/Concerns/SendsAttachmentsTest.php, tests/Unit/DTO/MessageTest.php, tests/Unit/DTO/VenueTest.php
close #310 venue implemented SendVenue Method and Venue DTO
=> #310 venue  Implemented SendVenue Method and Venue DTO

src/Keyboard/Keyboard.php
Wrong phpstan autocorrection of commit https://github.com/defstudio/telegraph/commit/e156746b0d864185b0def79e5cdf0a31725835bb
83275513591db2bafc6f0025fcfe030752cbd6e9
=> Incorrect array PHPDOC declaration in Keyboard::fromArray() method cause phpstan wrong autocorrection

docs/14.models/1.telegraph-bot.md
=> Just one minor typo in telegraph-bot.md

docs/12.features/9.dto.md, docs/12.features/payment.md, src/Concerns/InteractWithUsers.php, src/Concerns/InteractsWithPayments.php, src/DTO/Message.php, src/DTO/RefundedPayment.php, src/Models/TelegraphBot.php, src/Telegraph.php, tests/.pest/snapshots/Unit/Concerns/InteractsWithPaymentsTest/it_can_refund_star_payment_for_a_user.snap, tests/.pest/snapshots/Unit/Concerns/InteractsWithWebhooksTest/it_can_answer_pre_checkout_query.snap, tests/Unit/Concerns/InteractsWithPaymentsTest.php, tests/Unit/Concerns/InteractsWithWebhooksTest.php, tests/Unit/DTO/MessageTest.php, tests/Unit/DTO/RefundedPaymentTest.php
Star refunds were implemented in the Payments #704.
=> [feat] star refunds

.github/workflows/php-cs-fixer.yml, composer.json, phpstan.neon, src/Concerns/HasBotsAndChats.php, src/Concerns/ManagesKeyboards.php, src/DTO/Animation.php, src/DTO/Audio.php, src/DTO/CallbackQuery.php, src/DTO/ChatInviteLink.php, src/DTO/ChatJoinRequest.php, src/DTO/ChatMember.php, src/DTO/ChatMemberUpdate.php, src/DTO/Document.php, src/DTO/Entity.php, src/DTO/InlineQuery.php, src/DTO/Message.php, src/DTO/OrderInfo.php, src/DTO/PreCheckoutQuery.php, src/DTO/Reaction.php, src/DTO/Sticker.php, src/DTO/SuccessfulPayment.php, src/DTO/TelegramUpdate.php, src/DTO/Video.php, src/Handlers/WebhookHandler.php, tests/Pest.php
This pull request refactors the `WebhookHandler.php` file to improve its structure and readability. The functions are now reordered based on their priority and relevance, making the file easier to use and maintain. Overall, these changes improve the flow of the code and make future development simpler.
1. **Function Reorganization:**  
The functions are now arranged in a logical order based on priority and how they relate to each other.
This makes the code easier to understand and maintain.
2. **Refactored `handle()` Function:**  
The main `handle()` function has been rewritten to improve readability and to fix several issues:
- **`handleSuccessfulPayment` Issue (#704 ):**  
Previously, the `handleSuccessfulPayment` function was being triggered incorrectly, and both …
=> Fix Handlers

src/DTO/Chat.php, src/Handlers/WebhookHandler.php, tests/.pest/snapshots/Unit/Models/TelegraphBotTest/it_can_poll_for_updates.snap, tests/Unit/DTO/ChatTest.php
fix Chat DTO attributes.
[Doc URL](https://core.telegram.org/bots/api#chat)
=> Fix: Chat DTO Attributes
