defstudio/telegraph

README.md, composer.json, docs/content/en/features/keyboards.md, src/Concerns/InteractsWithTelegram.php, src/Concerns/ManagesKeyboards.php, src/Exceptions/KeyboardException.php, src/Facades/Telegraph.php, src/Keyboard/Button.php, src/Keyboard/Keyboard.php, src/Models/TelegraphChat.php, src/Proxies/KeyboardButtonProxy.php, src/Support/Testing/Fakes/TelegraphFake.php, tests/Unit/Concerns/ManagesKeyboardsTest.php, tests/Unit/Keyboard/KeyboardTest.php, tests/__snapshots__/ManagesKeyboardsTest__it_can_add_a_keyboard_as_a_closure__1.txt, tests/__snapshots__/ManagesKeyboardsTest__it_can_add_a_keyboard_as_an_array__1.txt, tests/__snapshots__/WebhookHandlerTest__it_extracts_call_data__1.yml
This PR will add the ability to define a Keyboard using a closure:
```php
Telegraph::message('hello world')
->keyboard(function(Keyboard $keyboard){
return $keyboard
->button('Delete')->action('delete')->param('id', '42')->width(0.5)
->button('Dismiss')->action('dismiss')->param('id', '42')->width(0.5)
->button('open')->url('https://test.it');
})->send();
```
credits to @cerbero90 for the cool idea :sunglasses:
=> Keyboard improvement

src/Handlers/WebhookHandler.php
This PR will avoid sending an `Unknown Command` feedback in non-private chats 
fix #51
=> fix: scoped exception on unknown commands

src/Models/TelegraphChat.php
=> Add edit method to TelegraphChat Model

docs/content/en/quickstart/sending-a-message.md
The strong closing tag was missed, resulting a bad request
=> Fix missing closing Tag in docs

src/DTO/Message.php
When user sent message with attached file, handler check only `text` field. But when file attached, `text` field replaced by `caption`.
=> Fix handler if message with document

docs/content/en/webhooks/dto.md, docs/content/en/webhooks/webhook-request-types.md, documentation_add_users_activity_handling.patch, src/DTO/Message.php, src/Handlers/WebhookHandler.php, tests/Pest.php, tests/Support/TestWebhookHandler.php, tests/Unit/DTO/MessageTest.php, tests/Unit/Handlers/WebhookHandlerTest.php
This PR will add two webhooks methods to override in order to handle group/supergroup  members joining and leaving:
```php
class CustomWebhookHandler extends WebhookHandler
{
protected function handleChatMemberJoined(User $member): void
{
$this->chat->html("Welcome {$member->firstName()}")->send();
}
protected function handleChatMemberLeft(User $member): void
{
$this->chat->html("{$member->firstName()} just left")->send();
}
}
```
closes #179
=> add users activity handling

src/Concerns/HasBotsAndChats.php, src/Models/TelegraphChat.php, src/Telegraph.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/Unit/Models/TelegraphChatTest.php, tests/__snapshots__/HasBotsAndChatsTest__it_can_leave_a_chat__1.yml
Implements methods for leaving a chat.
```php
Telegraph::chat($telegraphChat)->leaveChat();
$chat->leave();
```
This was not as straightforward as my last PR. Let me know if anything is in the wrong place, and I'll push a fix for you 👍
Closes #192
=> Implement `leaveChat` method

docs/content/en/features/telegram-api-calls.md, docs/content/en/models/telegraph-chat.md, src/Concerns/ComposesMessages.php, src/Facades/Telegraph.php, src/Models/TelegraphChat.php, src/Telegraph.php, tests/Unit/Concerns/ComposesMessagesTest.php, tests/Unit/Models/TelegraphChatTest.php, tests/__snapshots__/ComposesMessagesTest__it_can_forward_a_message__1.yml
Implements methods for forward a message.
`Telegraph::forwardMessage($fromChatId, $messageId)->send();`
Closes #184
=> [feat] forwardMessage method #184

docs/content/en/features/messages.md
Html messages only works with valid html
=> docs: Fix typo in messages section

config/telegraph.php, docs/content/en/installation.md, src/Concerns/InteractsWithWebhooks.php, tests/Unit/Concerns/InteractsWithWebhooksTest.php, tests/__snapshots__/InteractsWithWebhooksTest__it_can_register_a_webhook_with_a_custom_domain__1.yml
Adds a new `custom_webhook_domain` configuration key to force a different domain when registering a webhook
fix #254
=> [feat] custom webhook domain

docs/content/en/storage/entities_storage.md, src/Storage/CacheStorageDriver.php, src/Storage/FileStorageDriver.php, src/Storage/StorageDriver.php, tests/Unit/Storage/CacheStoreDriverTest.php, tests/Unit/Storage/FileStoreDriverTest.php
Telegraph can store model references as well: when a model is found inside data stored, it is internally converted in a class/id pair and the model is retrieved from DB when the value is fetched:
```php
/** @var \DefStudio\Telegraph\DTO\User $telegraphUser */
$systemUser = \App\Models\User::where('username', $telegraphUser->username());
$telegraphUser->storage()->set('system_data.user', $systemUser);
$telegraphUser->storage()->get('system_data.user') // will return an Instance of \App\Models\User 
```
=> [feat] model storage

src/Facades/Telegraph.php
fix #278 with the attribute cached as false, the resolvedInstance is no longer maintained
=> [fix] disable telegraph facade caching

docs/content/en/features/attachments.md, docs/content/en/features/telegram-api-calls.md, docs/content/en/models/telegraph-chat.md, docs/content/en/testing/assertions.md, src/Concerns/SendsAttachments.php, src/Facades/Telegraph.php, src/Models/TelegraphChat.php, src/ScopedPayloads/TelegraphEditMediaPayload.php, src/Support/Testing/Fakes/TelegraphEditMediaFake.php, src/Support/Testing/Fakes/TelegraphFake.php, src/Telegraph.php, tests/Unit/Concerns/SendsAttachmentsTest.php, tests/Unit/Models/TelegraphChatTest.php, tests/__snapshots__/SendsAttachmentsTest__it_can_edit_a_media_messages__1.yml, tests/__snapshots__/SendsAttachmentsTest__it_can_edit_a_media_messages_with_a_document__1.yml, tests/__snapshots__/SendsAttachmentsTest__it_can_edit_a_media_messages_with_a_photo__1.yml
close #268 implemented the method with relative docs and test (with snapshot). I need to know if the method input (the new media) must be a string or its better an object array and then convert it to json ( A JSON-serialized object is required in the Telegram Api). I'm gonna open a new issue for the Facade cache bug.
=> Issue #268 implement editMessageMedia method

src/DTO/Chat.php, tests/__snapshots__/TelegraphBotTest__it_can_poll_for_updates__1.yml
An integer data type is a non-decimal number between **-2147483648** and **2147483647** in 32 bit systems.
Currently, Telegram assigns _chat_ids_ greater than **2147483647** to new accounts, so they cannot be treated as `int` data by PHP without being distorted in 32 bit systems.
Using the `string` data type instead of `int` to handle the _chat_id_ could be a work around to this limitation and solve this issue  #284
=> [fix] chat_ids greater than 2147483647 in 32 bit systems

src/Concerns/ComposesMessages.php, src/Concerns/HasBotsAndChats.php, src/Concerns/InteractsWithTelegram.php, src/Concerns/ManagesKeyboards.php, src/Concerns/SendsAttachments.php, src/Concerns/StoresFiles.php, src/Facades/Telegraph.php, src/ScopedPayloads/TelegraphPollPayload.php, src/ScopedPayloads/TelegraphQuizPayload.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/__snapshots__/HasBotsAndChatsTest__it_can_customize_the_destination_chat_through_its_ID__1.yml, tests/__snapshots__/HasBotsAndChatsTest__it_can_register_commands_with_token__1.yml, tests/__snapshots__/HasBotsAndChatsTest__it_can_retrieve_bot_info_from_its_token__1.yml
this PR will enable the usage of telegraph without the need to create a TelegraphBot/TelegraphChat model, useful for simple projects
the bot/chat pair can both be set for each call:
`Telegraph::bot('TOKEN')->chat('ID')->message('hello')->send()`
and in configuration with `telegraph.bot_token` and `telegraph.chat_id`
ref #290
=> [feat] Model-less mode

src/Commands/UnsetTelegramWebhookCommand.php, tests/Feature/Commands/UnsetTelegramWebhookCommandTest.php
Fixes #321, there was a missing space between option name and its description
=> [fix] drop updates option missing in UnsetTelegramWebhookCommand

src/DTO/User.php, tests/Unit/DTO/MessageTest.php, tests/Unit/DTO/UserTest.php, tests/__snapshots__/TelegraphBotTest__it_can_poll_for_updates__1.yml
In some cases, Telegram sends the user's `language_code` key, and in some cases it doesn't.
I did not find the relationship from the settings, but this is a fact.
**Without key:**
```json
{
"message": {
"chat": {
"id": 12345,
"type": "supergroup",
"title": "Some Group",
"username": "some_group"
},
"date": 1677184219,
"from": {
"id": 123,
"is_bot": false,
"username": "foo",
"first_name": "Foo"
},
"text": "Some text 1",
"message_id": 925330
},
"update_id": 123456
}
```
**With key:**
```json
{
"message": {
"chat": {
"id": 12345,
"type": "supergroup",
"title": "Some Group",
"username": "some_group"
},
"date": 1677184343,
"from": {
"id": 234,
"is_bot": false,
"username": "bar",
"first_name": "Bar",
"language_code": "fr"
},
"text": "Some text 2",
"message_id": 925331
},
"update_id": 123457
} …
```
=> Added user parameter: "language_code"

docs/content/en/webhooks/webhook-request-types.md
Chat Commands Start With Slash (/) Not BackSlash (\\)  
[ /hi Fabio ] ✔️ 
[ \hi Fabio ] ❌
=> Chat Commands Start With Slash (/)

docs/content/en/features/keyboards.md, src/Keyboard/Keyboard.php, src/Keyboard/ReplyKeyboard.php, tests/Unit/Keyboards/KeyboardTest.php, tests/Unit/Keyboards/ReplyKeyboardTest.php
This pull request adds a new method called `rightToLeft` to the `Keyboard` and `ReplyKeyboard` classes. The `rightToLeft` method allows the user to flip the keyboard layout from left-to-right to right-to-left, and vice versa. This feature is particularly useful for languages that are written from right-to-left, such as Arabic, Persian, or Hebrew.
=> Feat: Add `rightToLeft` to `Keyboard` & `ReplyKeyboard`

src/Facades/Telegraph.php, src/Support/Testing/Fakes/TelegraphFake.php, tests/Regression/Issue-432-ClearTelegraphFakeFilesForNewRequestTest.php, tests/Unit/Storage/FileStoreDriverTest.php, tests/Unit/Storage/TestStorable.php
Issue https://github.com/defstudio/telegraph/issues/432
And refactor FileStoreDriverTest to pass tests in Windows
=> Fix telegraph fake attached files not clearing between fake requests (ISSUE-432)

composer.json
Starting with Larastan 2.7.0, the Larastan repository will now be managed under the Larastan organization.
=> Update composer.json to use Larastan Org

config/telegraph.php, docs/content/14.webhooks/2.registering-webhooks.md, docs/content/2.installation.md, routes/api.php
Allows to customize or disable the webhook URL via Telegraph Config File
fix  #471
=> custom webhooks url

docs/content/12.features/8.telegram-api-calls.md, src/Concerns/HasBotsAndChats.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/__snapshots__/HasBotsAndChatsTest__it_can_set_commands_bot_menu_button__1.yml
fix #479 allowing to call setChatMenuButton() without an active chat
=> [feat] allows to change a bot's default menu button

src/Proxies/KeyboardButtonProxy.php, src/Proxies/ReplyKeyboardButtonProxy.php
With these changes sequential keyboard property assignment will work properly:
```php
$telegraph->markdown('Registration needed')->replyKeyboard(
ReplyKeyboard::make()
->button('Send contact')->requestContact()
->button('Cancel')
->resize()
->oneTime()
->inputPlaceholder("Waiting for input")
)->send();
```
=> #549 add properties assignments in KeyboardButtonProxy and ReplyKeyboardButtonProxy constructors

database/migrations/create_telegraph_bots_table.php
enhances convenience and adds the ability to make migrate:rollback
=> Add "down" for rollback in "create_telegraph_bots_table"

database/migrations/create_telegraph_chats_table.php
increases convenience and adds the ability to make migrate:rollback
=> Add "down" for rollback in "create_telegraph_chats_table"

src/Concerns/HasBotsAndChats.php, tests/Pest.php, tests/Unit/Client/TelegraphResponseTest.php, tests/Unit/Support/Testing/TelegraphFakeTest.php
defers chat retrieval until it is actually used
fix #568
=> teletraph chat retrieve optimization

src/Handlers/WebhookHandler.php
I had an issue with getting an error when returning an action from a keyboard button.
I tracked it down to this line
https://github.com/defstudio/telegraph/blob/231947e26930e258e79e5ce2e79c2163eac2c81d/src/Handlers/WebhookHandler.php#L276-L277
It seems there is an issue here if `$this->message` isnt available.
I simply pulled out the `message` check into an if block to make it clearer and also to avoid the error.
With this the code runs fine.
I am unsure how to run your tests, perhaps you might let me know or run them and see if there is an extra issue.
Thanks
=> [fix] message not set up before retrieving Chat

src/DTO/User.php, tests/Regression/Issue-619-NullFirstNameTest.php
I got an error today that some of the **first_name** in the **left_chat_member** object is null
I think when a deleted account removed from group, the first name is null
I had to return null safe to first_name to avoid generating an error
=> Fix UserDTO

config/telegraph.php, src/Concerns/FakesRequests.php, src/Facades/Telegraph.php, src/Handlers/WebhookHandler.php, src/Support/Testing/Fakes/TelegraphFake.php, tests/Unit/Handlers/WebhookHandlerTest.php
This change will allow you to move away from the usual commands starting with the `/` symbol using any form the developer wishes.
For example:
```php
// config/telegraph.php
return [
'commands' => [
'start_with' => ['-', '!', ' % ', 1],
],
];
```
These are the commands:
```
/hello@bot foo bot
-hello@bot foo bot
!hello@bot foo bot
%hello@bot foo bot
1hello@bot foo bot
```
They're not commands:
```
\hello@bot foo bot
]hello@bot foo bot
[hello@bot foo bot
_hello@bot foo bot
```
The `/` character will be used by default in any case.
=> Added the ability to specify different prefixes for command definitions

src/Handlers/WebhookHandler.php
The main problem with private methods is that they cannot be overridden.
By default, the `handleCommand` method looks for commands starting with `/`, but what if they have different names? For example, `/start`, `!start`, `:start`?
Of course, it is possible to add this functionality to this package, but it would be better done in another PR.
Now, why `protected`? Because I can't override private methods, I have to also override other methods that call them. So on the output I get a copypaste of the `WebhookHandler` class with minor changes instead of doing it this way:
```php
abstract class Webhook extends WebhookHandler
{
protected function handleCommand(Stringable $text): void
{
$command   = (string) $text->after('/')->after('!')->before(' ')->before('@');
$parameter = (string) …
```
=> Make protected methods

src/Handlers/WebhookHandler.php
The current version of the code hardcodes the name of the chat when saving to the database. For example, `[supergroup] Foo`.
This is inconvenient when you need to display the list of channels without prefixes.
In such cases we have to create casts for the `name` field of the model to apply a regular expression to remove the prefix.
To solve this problem, I propose to consider two interrelated actions at once:
1. Put the formation of the chat name into an external protected method that developers can easily override to change the logic.
2. also put the method of chat creation into an external method in case some of the developers need to add their own logic when saving, having access to the `DefStudio\Telegraph\DTO\Chat` object.
=> Added independent methods for saving a chat and forming its name

config/telegraph.php, docs/15.webhooks/4.webhook-request-types.md, src/Concerns/InteractsWithWebhooks.php, src/DTO/Reaction.php, src/Handlers/WebhookHandler.php, tests/Pest.php, tests/Support/TestWebhookHandler.php, tests/Unit/DTO/ReactionTest.php, tests/Unit/Handlers/WebhookHandlerTest.php
By default Telegram sends all events except `chat_member`, `message_reaction`, and `message_reaction_count`.
Therefore, you need to explicitly set the required message types, such as `message_reaction`, to receive them.
Docs: https://core.telegram.org/bots/api#setwebhook
=> Adding reaction processing when retrieving in webhooks

src/Handlers/WebhookHandler.php, tests/Unit/Handlers/WebhookHandlerTest.php
This PR fixes an error when a command is passed without parameters, such as `/foo`. In this case, the parameter will be `/foo` and the command name will be `foo`.
As a bonus, the command eliminates processing all other prefixes from the array when the right one is found.
Examples:
```json
{
"message": {
"chat": { "id": -111, "type": "supergroup", "title": "Test Group" },
"date": 1727723329,
"from": { "id": 222, "is_bot": false, "last_name": "Doe", "first_name": "John" },
"text": "/foo bar",
"entities": [
{ "type": "bot_command", "length": 4, "offset": 0 }
],
"message_id": 1854
},
"update_id": 1
}
```
```
Hello!! your parameter is [bar]
```
```json
{
"message": {
"chat": { "id": -111, "type": "supergroup", "title": "Test Group" },
"date": 1727723329,
"from": { "id": 222, "is_bot": false, …
```
=> Fix detection of command parameter without passing it

docs/12.features/9.dto.md, src/DTO/Entity.php, src/DTO/Message.php, tests/.pest/snapshots/Unit/Models/TelegraphBotTest/it_can_poll_for_updates.snap, tests/Support/TestEntitiesWebhookHandler.php, tests/Unit/DTO/EntityTest.php, tests/Unit/DTO/MessageTest.php, tests/Unit/Handlers/WebhookHandlerTest.php
Message entities can provide a lot of useful information. For example:
- mention
- hashtag
- cashtag
- bot_command
- url
- email
- phone_number
- bold
- italic
- underline
- strikethrough
- spoiler
- blockquote
- expandable_blockquote
- code
- pre
- text_link
- text_mention
- custom_emoji
In other words, they contain not only rules for styling messages, but also useful data. For example, a phone number, link or hashtag found in the message body, based on which the application can apply certain rules of message processing.
Documentation: https://core.telegram.org/bots/api#messageentity
=> Added entities processing

src/DTO/Entity.php
Interesting point - the documentation says this field is a string, but the webhook comes up with an integer:
```json
{
"message":{
"text":"💗 foo",
"entities":[
{
"type":"custom_emoji",
"length":2,
"offset":0,
"custom_emoji_id":5364201435858744869
}
],
"message_id":68753
},
"update_id":577883599
}
```
_I removed the extra fields so they wouldn't be distracting._
Since I'd rather stick to the official documentation, I specified a conversion to a string when assigning the identifier.
=> TypeError: Cannot assign int to property `Entity::$customEmojiId` of type ?string

src/Keyboard/Keyboard.php
Telegram swap empty query string with null value for InlineKeyboardButton. When you send switch_inline_query_current_chat='', on Callback you receive data with button with switch_inline_query_current_chat=null.
https://github.com/defstudio/telegraph/issues/658
=> fix error in Keyboard::fromArray() method if InlineKeyboardButton button has empty query string

src/Concerns/ComposesMessages.php, src/Concerns/HasBotsAndChats.php, src/Concerns/InteractsWithTelegram.php, src/Concerns/InteractsWithWebhooks.php, src/Concerns/SendsAttachments.php, src/Concerns/StoresFiles.php
PHP 8.4 deprecates implicitly nullable parameter types. This update explicitly declares nullable types (`?type`) to ensure compatibility and eliminate deprecation warnings.
=> fix: Implicitly nullable parameter types in php8.4

docs/12.features/9.dto.md, docs/15.webhooks/4.webhook-request-types.md, src/DTO/InlineQueryResultVenue.php, tests/.pest/snapshots/Unit/Concerns/AnswersInlineQueriesTest/it_can_answer_an_inline_query.snap, tests/.pest/snapshots/Unit/Concerns/AnswersInlineQueriesTest/it_can_offer_to_switch_to_private_message.snap, tests/.pest/snapshots/Unit/Concerns/AnswersInlineQueriesTest/it_can_set_cache_duration.snap, tests/.pest/snapshots/Unit/Concerns/AnswersInlineQueriesTest/it_can_set_next_offset.snap, tests/.pest/snapshots/Unit/Concerns/AnswersInlineQueriesTest/it_can_set_results_as_personal.snap, tests/Unit/Concerns/AnswersInlineQueriesTest.php, tests/Unit/DTO/InlineQueryResultVenueTest.php
Implement InlineQueryResultVenue
=> Implement InlineQueryResultVenue

src/DTO/ReactionType.php, tests/Unit/DTO/ReactionTest.php
Ran into an issue today where Telegram sent the `custom_emoji_id` property without `emoji`:
```json
{
"update_id":61801077,
"message_reaction":{
"chat":{
"id":-1002362140004,
"title":"Ковёр не самолёт",
"username":"covernesamolet",
"type":"supergroup"
},
"message_id":3794,
"user":{
"id":107679035,
"is_bot":false,
"first_name":"Dalert",
"last_name":"Zart Okderin",
"username":"DalertDragon",
"is_premium":true
},
"date":1734843802,
"old_reaction":[],
"new_reaction":[
{
"type":"custom_emoji",
"custom_emoji_id":"5425057201137918413"
}
]
}
}
```
This PR fixes that problem.
=> Fixed Undefined array key "emoji"

src/Client/TelegraphResponse.php
Methods dump and dd with $key parameter were added in Laravel 11 in Illuminate\Http\Client\Response class.
So, now there is an error:
`Fatal error:  Declaration of DefStudio\Telegraph\Client\TelegraphResponse::dump(): static must be compatible with Illuminate\Http\Client\Response::dump($key = null)`
Laravel 11
https://github.com/laravel/framework/blob/11.x/src/Illuminate/Http/Client/Response.php
Laravel 10
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Http/Client/Response.php
=> Fix error in DefStudio\Telegraph\Client\TelegraphResponse dump() and dd() methods declaration

resources/lang/ru/errors.php
Missing key detected and translated 🙂
=> Translation of the missing key `webhook_error_occurred` into Russian

src/Handlers/WebhookHandler.php, tests/Unit/Concerns/HasBotsAndChatsTest.php, tests/Unit/Handlers/WebhookHandlerTest.php
I'm surprised I haven't encountered this before.....
In general, over the last two days I've encountered a collision of custom commands, as a result of which a message is defined as a command.
For example:
```php
// config/telegraph.php
return [
// ...
'commands' => [
'start_with' => ['/', '!'],
],
];
```
```json
{
"message": {
"chat": { "id": -111, "type": "supergroup", "title": "Test Group"},
"date": 1727720853,
"from": { "id": 333, "is_bot": false, "first_name": "John"},
"text": "!!!Some message",
"message_id": 1854
},
"update_id": 577874479
}
```
The current version of the Telegraph would define this as a command:
```php
dd([
'command' => '!!Some',
'parameter' => 'message',
]);
```
The proposed fix adds collision checking for commands, taking into account the fact that a command can …
=> Fixed a collision of custom command prefixes

src/DTO/TelegramUpdate.php, src/Handlers/WebhookHandler.php, tests/Unit/DTO/TelegramUpdateTest.php
set edited_channel_post data like as channel_post data.
edited_channel_post only has an extra attribute called edit_date.
=> Fix: Edit channel post

src/Facades/Telegraph.php, src/Models/TelegraphBot.php, src/Models/TelegraphChat.php, src/Telegraph.php, tests/Unit/Models/TelegraphBotTest.php, tests/Unit/Models/TelegraphChatTest.php
I implemented a new method called `withEndpoint()` so that we can set custom endpoints.
Why?
- We can quickly implement methods that are not implemented, without having to contribute.
- I use this package for another messenger (for our country), and it almost follows the structure of Telegram. It has a few different methods from Telegram, and this is how I can use them.
=> Feat: Can send custom endpoint request
